---
title: Detection of extreme heatwaves and low sea ice cover in the Antarctic Peninsula  for evaluation of effects over Krill, Part II - process and analyse downloaded data
author: "Lucas Krüger, Maurício Mardones, Lorena Rebolledo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#---------- Download NOAA erddap optimum interpolation SST----

#this part of the script is a modification of the scripts in the heatwaveR vignette
#available at https://robwschlegel.github.io/heatwaveR/articles/OISST_preparation.html


```{r, echo =FALSE}
#---------- Download NOAA erddap optimum interpolation SST----

# The packages we will use
library(dplyr) # A staple for modern data management in R
library(lubridate) # Useful functions for dealing with dates
library(ggplot2) # The preferred library for data visualisation
library(patchwork)
library(tidync) # For easily dealing with NetCDF data
library(rerddap) # For easily downloading subsets of data
library(doParallel) # For parallel processing
library(raster)
library(terra)
library(sf)

library(mapdata)
library(mapproj)

library(reshape2)

```


###----------- calculating marine heatwaves-------------

### load and process krill data

```{r}

  
krill.strata<-readRDS("KrillData.Rdata") 


krill.strata$timestamp<-as.POSIXct(strptime(krill.strata$datetime_set_start, format="%Y-%m-%d %H:%M:%S", tz="GMT"))

krill.strata$Week<-week(krill.strata$timestamp)
krill.strata$Year<-year(krill.strata$timestamp)
krill.strata$Month<-month(krill.strata$timestamp)
krill.strata$Quarter<-quarter(krill.strata$timestamp)

krill.strata$Season[krill.strata$Quarter=="1"]<-"JFM"
krill.strata$Season[krill.strata$Quarter=="2"]<-"AMJ"
krill.strata$Season[krill.strata$Quarter=="3"]<-"JAS"
krill.strata$Season[krill.strata$Quarter=="4"]<-"OND"

krill.strata$sector<-krill.strata$ID


krill.strata$stage<-as.factor(krill.strata$maturity_stage)

krist<-na.omit(data.frame(krill.strata[13],krill.strata[,16:23]))

#correct strata name to match the climatology data

krist$sector[krist$sector=="Extra"]<-"EX"
krist$sector[krist$sector=="SSIW"]<-"SS"

krist$Talla<-ifelse(krist$length_total_cm<4,"Recruit","Adult") # first step to calculate the recruitment index


ad<-(plyr::ddply(krist, c("Year","sector"), summarise,
                        Ntot=length(na.omit(length_total_cm))))  # number of adults

rec<-(plyr::ddply(subset(krist,Talla=="Recruit"), c("Year","sector"), summarise,
                        Nrec=length(na.omit(length_total_cm))))  # number of recruiters


recind<-merge(ad,rec,all.x=TRUE)  # merge to calculate recruitment index

recind$Nrec[is.na(recind$Nrec)]<-0


recind$recind<-recind$Nrec/recind$Ntot  # recruitment index

summary(recind$Year)


ggplot(recind,aes(Year,recind))+
  geom_smooth(se=F,method="gam")+
  geom_point()+
  #facet_wrap(sector~.)+
  theme_bw()+ylab("Proportion of recruiting individuals")+xlim(2000,2015)

```



```{r}

chlall<-base::readRDS("CHL_summer.Rds")

climS<-base::readRDS("climatologyICE.Rds")
climT<-base::readRDS("climatologyTEMP.Rds")

summary((year(climS$t)))

climS$Year<-year(climS$t)
climS$Month<-month(climS$t)
climS$Quarter<-quarter(climS$t)

climT$Year<-year(climT$t)
climT$Month<-month(climT$t)
climT$Quarter<-quarter(climT$t)



climWS<-plyr::ddply(subset(climS,Quarter=="2"|Quarter=="3"), c("Year","sector"), summarise,
                    SICPeak=max(na.omit(sicMean)),SICmean=mean(na.omit(sicMean)),Sthresh=mean(na.omit(thresh)))

climST<-plyr::ddply(subset(climT,Quarter=="1"|Quarter=="4"), c("Year","sector"), summarise,
                    
                    TempMax=max(na.omit(tMax)),TempMean=mean(na.omit(tMax)),Tthresh=mean(thresh))

climWS<-merge(climWS,climST)

head(climWS)

evesum<-base::readRDS("events_summary.Rds")

eveclim<-merge(evesum,climWS,all=T)

mean(chlall$chlm)

ecc<-merge(eveclim,chlall,all=T)

chlk<-merge(ecc,recind)


head(chlk)

chlk$sicc<-ifelse(chlk$SICmean<median(na.omit(chlk$SICmean)),"Low","High")
chlk$tempc<-ifelse(chlk$TempMean<median(na.omit(chlk$TempMean)),"Low","High")

chlk$SN[is.na(chlk$SN)]<-0

chlk$siceve[chlk$SN=="0"]<-"None"
chlk$siceve[chlk$SN=="1" |chlk$SN=="2"]<-"One or Two"
chlk$siceve[is.na(chlk$siceve)]<-"Three or more"


chlk$TN[is.na(chlk$TN)]<-0

chlk$tempeve[chlk$TN=="0"]<-"None"
chlk$tempeve[chlk$TN=="1" |chlk$SN=="2"]<-"One or Two"
chlk$tempeve[is.na(chlk$tempeve)]<-"Three or more"

chlk$TcumDur[is.na(chlk$TcumDur)]<-0
chlk$ScumDur[is.na(chlk$ScumDur)]<-0

chlk$TmeanInt[is.na(chlk$TmeanInt)]<-0
chlk$SmeanInt[is.na(chlk$SmeanInt)]<-0


# ----- permutation analysis with the pgirmess package----------


lm01<-lm(recind~sicc,data=chlk)
summary(lm01)
pgirmess::PermTest(lm01,B=1000)

lm02<-lm(recind~siceve,data=chlk)
summary(lm02)
pgirmess::PermTest(lm02,B=1000)

lm03<-lm(recind~tempc,data=chlk)
summary(lm03)
pgirmess::PermTest(lm03,B=1000)


lm04<-lm(recind~tempeve,data=chlk)
summary(lm04)
pgirmess::PermTest(lm04,B=1000)


lm05<-lm(recind~chlc,data=chlk)
summary(lm05)
pgirmess::PermTest(lm05,B=1000)



#-----plot---------

ggplot(chlk,aes(sicc,recind))+geom_boxplot(fill="grey70")+
theme_bw()+xlab("")+ylab("KRI")+
  ggtitle(label="a. Winter sea ice cover")+

ggplot(chlk,aes(tempc,recind))+geom_boxplot(fill="grey70")+
  theme_bw()+xlab("")+ylab("")+
  ggtitle(label="b. Summer sea surface temperature")+

ggplot(chlk,aes(tempeve,recind))+geom_boxplot(fill="grey70")+
  theme_bw()+xlab("")+ylab("KRI")+
  ggtitle(label="c. Occurrence of extreme events")+

ggplot(chlk,aes(chlc,recind))+geom_boxplot(fill="grey70")+
  theme_bw()+xlab("")+ylab("")+
  ggtitle(label="d. Chlorophyll-a concentration")




```
